openapi: 3.0.3
info:
  title: API
  version: 1.0.0

paths:
  /users:
    $ref: './paths/users/get-users.yaml'
  /users/create:
    $ref: './paths/users/create-user.yaml'

components:
  schemas:
    User:
      $ref: './types/user.yaml#/User'
    Address:
      $ref: './types/address.yaml#/Address'